version: '1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9080:8080
    depends_on:
      - db
    environment:
      - "KC_HEALTH_ENABLED=true"
      - "KC_METRICS_ENABLED=true"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://db:5432/keycloak"
      - "KC_DB_USERNAME=postgres"
      - "KC_DB_PASSWORD=postgres"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
    command: start-dev --import-realm --log-level=INFO --hostname-debug true
    hostname: keycloak.local
    volumes:
      - ./ecosystem.json:/opt/keycloak/data/import/ecosystem.json
      - ../keycloak-custom-event-listener/target/custom-event-listener.jar://opt/keycloak/providers/custom-event-listener.jar
    networks:
      - social-network-ecosystem
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER:
      POSTGRES_DB: resume
    ports:
      - 5443:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - social-network-ecosystem


      
networks:
  social-network-ecosystem:
    driver: bridge
    name: social-network-ecosystem
