version: '1'

services:
  keycloak:
    image: local-keycloak
    ports:
      - 9080:8080
    depends_on:
      - db
    hostname: keycloak.local
    networks:
      - social-network-ecosystem
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER:
      POSTGRES_DB: resume
    ports:
      - 5443:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - social-network-ecosystem
      
networks:
  social-network-ecosystem:
    driver: bridge
    name: social-network-ecosystem
